### ISSUE TITLE
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

### ISSUE THREAD

**Issue by marisolosman** [jswhit/pygrib#101]
I tried to import pygrib and I got this message

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

these are the versions of numpy and pygrib

numpy                     1.11.2                   py35_0    anaconda
pygrib                    2.0.3            py35h5688137_0    conda-forge

Any idea how to fix it?

**Comment by akrherz** [comment]
You should consider running a pure `conda-forge` environment.  See [conda-forge gotchas](https://conda-forge.org/docs/conda-forge_gotchas.html)

**Comment by marisolosman** [comment]
I upgraded numpy (using anothe channel, not conda forge) and I solved it
