### ISSUE TITLE
Differences in the latitudes of pygrib and wgrib2 on GFS surface flux grib files

### ISSUE THREAD

**Issue by fepeacock70** [jswhit/pygrib#102]
I have found differences of the latitude outputed by pygrib and wgrib2 (a grib reading utility created by Wesley Ebisuzaki) for the current GFS and parallel FV3 GFS surface flux grib files. The version of wgrib2 I used is v0.2.0.5 7/2016. The versions of pygrib I have tested against are 2.0.1 and 2.0.2-3.

In particular, the test case is for today's 00Z run (2019-02-07) of the operational GFS and FV3, and the variable is WEASD on the surface flux grid for forecast hour 03. I have selected a single point in the UK where snow is presently lying.

I have attached screenshots of the processing.

What appears to be the case is that the latitudes are slightly different when using pygrib and wgrib2/grib filter on the operational GFS. The same differences are true when using the FV3 data. Note that pygrib values for the latitude agree with wgrib only on the grib filtered output from the current operational GFS.

Could you please inform me as to which is correct - wgrib2 or pygrib?

Many thanks,

Frank

![wgrib on whole world current gfs](https://user-images.githubusercontent.com/46676576/52427597-481b2180-2b26-11e9-8b36-cb5ac2aa70b3.png)
![wgrib on current gfs grib filtered file](https://user-images.githubusercontent.com/46676576/52427599-481b2180-2b26-11e9-9089-5582530e125e.png)
![wgrib2 on fv3](https://user-images.githubusercontent.com/46676576/52427600-48b3b800-2b26-11e9-9c84-29445fa9a3fd.png)
![pygrib on whole world current gfs](https://user-images.githubusercontent.com/46676576/52427601-48b3b800-2b26-11e9-92ee-2a6ed78aab5e.png)
![pygrib on fv3](https://user-images.githubusercontent.com/46676576/52427602-48b3b800-2b26-11e9-89f7-e71000b76911.png)
![pygrib on current gfs grib filtered file](https://user-images.githubusercontent.com/46676576/52427603-494c4e80-2b26-11e9-961e-aa1636861eed.png)

**Comment by jswhit** [comment]
Don't know. The latitudes and longitudes are not actually encoded in the grib file - only the parameters that define the grid.  Apparently wgrib2 and pygrib are either intrepreting the parameter differently, or using different code for computing gaussian quadrature points.

**Comment by jswhit** [comment]
@fepeacock70, could you zip an example grib file and upload it to this ticket so I can begin to debug this?

**Comment by fepeacock70** [comment]
Hello,

Since the grib2 files on the NCEP https site are large, I will rather add a link to download the file, rather than attach the file. An example grib2 file can be found at: https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.2019021212/gfs.t12z.sfluxgrbf115.grib2

Any message from this file will suffice.

Thanks,

Frank

**Comment by jswhit** [comment]
Frank - I've got a potential fix in pull request #103.  Turns out that there we some kludgy workarounds in the code to deal with bugs in older version of the grib-api library that are no longer needed.  Simply commenting them out seems to have fixed the problem.  I think you will find you get the same answer as wgrib2 now (at least to 6 or 7 decimal places).

**Comment by jswhit** [comment]
The pull request was merged.  Do you need me to make a new release before you can use it?

**Comment by fepeacock70** [comment]
Yes, please.

**Comment by jswhit** [comment]
Done.
