### ISSUE TITLE
floor division in pygrib.pyx

### ISSUE THREAD

**Issue by mhagdorn** [jswhit/pygrib#113]

**Comment by mhagdorn** [comment]
building pygrib with python3.6 I found an issue in _get_grib_api_version. rather than divide you should use the floor division operator:

--- pygrib.pyx-orig     2019-05-31 14:44:02.437481979 +0100
+++ pygrib.pyx  2019-05-31 14:44:10.375653977 +0100
@@ -297,7 +297,7 @@
 #missingvalue_float = GRIB_MISSING_DOUBLE
 missingvalue_float = -1.e100 # value given in grib_api.h version 1.90
 def _get_grib_api_version():
-    div = lambda v,d: (v/d,v%d)
+    div = lambda v,d: (v//d,v%d)
     v = grib_get_api_version()
     v,revision = div(v,100)
     v,minor = div(v,100)

**Comment by jswhit** [comment]
Thanks - would you mind creating a PR?

**Comment by mhagdorn** [comment]
done
