### ISSUE TITLE
Grib1 to Grib2 conversion

### ISSUE THREAD

**Issue by exfizik** [jswhit/pygrib#12]
Is it possible to convert a grib1 file to grib2 using pygrib?
This is not really an issue, just a question. 

Thanks!

**Comment by jswhit** [comment]
Yes, there is a cnvgrib1to2 utility.  It sort of works, but not always, since not all grib1 messages can be converted to grib2 (since there isn't always enough information in a grib1 message to define how to do the conversion).

**Comment by exfizik** [comment]
Oh, that's handy. Thanks!
