### ISSUE TITLE
latlons() grid in wrong direction when jScansPositively == 0

### ISSUE THREAD

**Issue by thorsteinssonh** [jswhit/pygrib#128]
I found that with certain grib files where the grid is organized with the first grid point in top left corner, i.e. jScansPositively = 0, the grid is still calculated as if the first grid point is bottom left.  I looked at the code for latlons() in pygrib.pyx and found that some logic was missing to invert the dx/dy increment accordingly.

I have made a fork and am making a pull request with this fix, but I started only fixing it for the lambert grid, I think this is probably an issue with all the projection types -- perhaps you can check and see if my fix is appropriate, or if you want to do it another way.  My fix in the lambert grid section looks like this:

```python
            # Set increment direction here for the grid.
            # NOTE: some GRIB files are arranged with first gridpoint
            # in top left, or top right corner for example...
            if self['iScansPositively'] == 0: dx = -dx
            if self['jScansPositively'] == 0: dy = -dy

            x = llcrnrx+dx*np.arange(nx)
            y = llcrnry+dy*np.arange(ny)
```

**Comment by thorsteinssonh** [comment]
Btw, I first checked that this was not an issue with latest ECCODES vs GRIB_API. Same error in both cases, so traced it down to the actual latlong() method in pygrib.pyx

**Comment by thorsteinssonh** [comment]
OK I have submitted a pull request to master,  branch named issue128_... 
Note however, I have only done a fix to lambert -- If you approve I can apply the same change to all the projection types.  Just let me know.

**Comment by thorsteinssonh** [comment]
Btw, if you want an example grib file with this issue, here is a link for you to download. It's a forecast from the Icelandic Met Office exported from IBL Visual Weather -- IBL seems to like first grid point in top left corner:
http://brunnur.vedur.is/pub/hrafng/tmp/test/IMOX_2020011412.grb

**Comment by jswhit** [comment]
If you have time, please do go ahead and submit a PR for the other projections.

**Comment by thorsteinssonh** [comment]
Thanks, great, will do that in the next few days and issue another pull.
Pygrib is a great asset for us, thank you so much for the work!
