### ISSUE TITLE
installing in newer python versions

### ISSUE THREAD

**Issue by wumpus** [jswhit/pygrib#133]
Every time python does a major revision, Cython changes and files like pygrib.c need to be updated. I just installed on Python 3.7.3 and this command did the trick:

`python setup.py build_ext --inplace`

In theory you could update the checked-in .c files with the latest Cython and it'll be back-compatible.

**Comment by cristi-neagu** [comment]
I installed this library with conda, from conda-forge. It installed well (at least according to conda), it imports, it seems to read grib files, but it says they're empty. Would this have to do with this issue you're describing? Do i have to manually build the module?

**Comment by wumpus** [comment]
It shouldn't be -- having an old cython version to build the code means that the C code it generates doesn't compile. That should have stopped pygrib's install.

I'm not a conda user, sorry.

**Comment by jswhit** [comment]
setup.py will use cython to re-generate pygrib.c if cython is installed.

**Comment by wumpus** [comment]
Reading through the setuptools/Cython docs I see that this is normal, however, the other packages I use keep up with python versions so that a vanilla "pip install" doesn't need cython installed in advance.

Now that 3.9 is almost here, there will probably be some new folks being confused.
