### ISSUE TITLE
Manual build fails

### ISSUE THREAD

**Issue by vtoupet** [jswhit/pygrib#135]
It fails building (python setup.py build) due to this error:

```
Traceback (most recent call last):
  File "setup.py", line 194, in <module>
    this_directory = path.abspath(path.dirname(__file__))
NameError: name 'path' is not defined
```

It looks like `os.`is missing.

**Comment by jswhit** [comment]
This traceback is not coming from pygrib (there are no such lines in pygrib's setup.py)

**Comment by vtoupet** [comment]
I've just verified and the line is there since commit https://github.com/jswhit/pygrib/commit/ebe34a689d2188ced36ccb85907e785fc9413e4b (January 22).
