### ISSUE TITLE
pygrib setup.py issue

### ISSUE THREAD

**Issue by calvin272m** [jswhit/pygrib#137]
I followed an instruction of installing pygrib. but the last part of installing the pygrib, I had the following issue:
Traceback (most recent call last):
  File "setup.py", line 194, in <module>
    this_directory = path.abspath(path.dirname(__file__))
NameError: name 'path' is not defined

the instruction I referred to is the link as followed:
https://gist.github.com/emmanuelnk/406eee50c388f4f73dcdff521f2aa7b2

I don't know how to fix it? 
hope some friends could help me fix this problem, since I am in an urgent need of pygrib to decode the data. Thanks a lot.

**Comment by akrherz** [comment]
Same issue as #135 and appears to be a result of PR #130 merged a few months ago.
