### ISSUE TITLE
pygrib setup.py issues

### ISSUE THREAD

**Issue by calvin272m** [jswhit/pygrib#139]
![image](https://user-images.githubusercontent.com/63885214/79689822-83030400-8257-11ea-8f62-c883e83fca52.png)
This is the issue what I got when I tried to install pygrib in my computer by using an online instruction. 
https://gist.github.com/emmanuelnk/406eee50c388f4f73dcdff521f2aa7b2
referring to the #130 , it lacked the long_description for the readme.md, but in my setup.py file, i do have the added lines indicated in #130. still it raises the issue of path not defined. 
I set the environment variable in the terminal ~/.bash_profile. 
then, I uncomment the lines of grib_api_dir=/~/../eccodes/(which is my own home directory), also I uncomment the last line "grib_api_libname=eccodes"
I did everything, but still it has the path problem, could someone kindly help me solve this? 
Thanks a lot

**Comment by akrherz** [comment]
@calvin272m edit `setup.py` and on lines 193-196, replace any `path.` usage with `os.path.` or see the diff [here](https://github.com/jswhit/pygrib/pull/138/commits/04308a40e3da34e2d17c67da8b855efec7b5393a)

**Comment by calvin272m** [comment]
Thanks Akrherz
but when I changed the path setting, it just came up with new issue listed as followed:
error: command 'gcc' failed with exit status 1
![image](https://user-images.githubusercontent.com/63885214/79690848-ef343680-825c-11ea-8d0e-4f96f07e6a43.png)
I

**Comment by akrherz** [comment]
@calvin272m you have to have the grib_api installed, see the `README.md`

**Comment by jswhit** [comment]
This bug in setup.py that was introduced in PR #130 is fixed now in master
