### ISSUE TITLE
Preferences for Citing Pygrib?

### ISSUE THREAD

**Issue by mariandob** [jswhit/pygrib#143]
Hello,

I am looking to see if there are any specific papers that I should cite for using Pygrib, or if the author(s) of Pygrib have any specific preferences of how they would like the package cited within a publication?

Here is an idea I was thinking in APA format for citing the software directly:

Whitaker, J., (2010). Pygrib: Python interface for reading and writing GRIB files. _Version 2.0.4_ , [Available online at https://github.com/jswhit/pygrib] 

This is not really an "issue", so feel free to label this appropriately (question?).

Thanks for your time and for this great package.

Best,

Marian

**Comment by jswhit** [comment]
You can use zenodo 

https://zenodo.org/record/4292914#.X8FC_qpKjZM
