### ISSUE TITLE
'Function not yet implemented' error when reading GRIB2 values

### ISSUE THREAD

**Issue by grwise1** [jswhit/pygrib#145]
I have been using pygrib to successfully read HRRR and NAM data from the ncep servers. However I am getting an error when attempting to read the RAP data:

Traceback (most recent call last):
  File "C:\Users\grwis\Miniconda3\hrrr_xarray.py", line 90, in <module>
    sfc_cape = grb.values
  File "pygrib.pyx", line 843, in pygrib.gribmessage.__getattr__
  File "pygrib.pyx", line 1259, in pygrib.gribmessage.__getitem__
RuntimeError: b'Function not yet implemented'

Code:
`grbs = pygrib.open('ftp://ftp.ncep.noaa.gov/pub/data/nccf/com/rap/prod/rap.20200823/rap.t00z.awp130pgrbf01.grib2')
grbs.seek(0)

grb = grbs.message(267)
sfc_cape = grb.values`

Anyone able to offer help with this? I am stumped as to why the RAP grib file could be doing this. It appears to be very similar structure to the NAM and HRRR....

**Comment by akrherz** [comment]
Works for me on Linux 64bit, python 3.8, pygrib 2.0.5.  Can you share more about what version of pygrib you have installed?  Are you able to reproduce the issue on Linux?

**Comment by grwise1** [comment]
Okay, thanks for checking into it. I currently run on Windows, but may need to consider installing a Linux system. I have found a lot of these python grib packages are better supported on Linux. I will pursue that route to see if I can resolve this error.
