### ISSUE TITLE
can pygrib be installed on Mac? 

### ISSUE THREAD

**Issue by zhengkai15** [jswhit/pygrib#146]
can pygrib be installed on Mac? 

python setup.py build
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    raise ImportError("either pyproj or basemap required")
ImportError: either pyproj or basemap required

**Comment by jswhit** [comment]
Yes, but it requires the pyproj module be installed first.

**Comment by jswhit** [comment]
There is also a macports port (py-pygrib)

**Comment by jswhit** [comment]
and an anaconda package https://anaconda.org/conda-forge/pygrib
