### ISSUE TITLE
Pygrib v2.0.5 not available through pip

### ISSUE THREAD

**Issue by basanaz** [jswhit/pygrib#147]
The latest version of pygrib that can be installed through [pip ](https://pypi.org/project/pygrib/) seems to be version 2.0.4. 

Could version 2.0.5 be uploaded to PyPI as well?

**Comment by jswhit** [comment]
Done

**Comment by fox91** [comment]
Actually isn't available.
Latest version is `2.0.4` https://pypi.org/project/pygrib/#history

```bash
$ pip search pygrib
pygrib (2.0.4)      - Python module for reading/writing GRIB files
```

**Comment by jswhit** [comment]
really done now

**Comment by fox91** [comment]
Confirmed.
Thanks
