### ISSUE TITLE
ECMWF GRIB API Documentation No Longer Available

### ISSUE THREAD

**Issue by maxshowarth** [jswhit/pygrib#149]
https://github.com/jswhit/pygrib/blob/00c1423d21416587e0f8a2d5bb76d96cfffd2a9e/pygrib.pyx#L797-L806

Referenced documentation from ECMWF about the GRIB Message keys is no longer available at the provided URLs. 

I believe that much of the documentation has been taken offline - some old copies seem to be available here: 
1. https://confluence.ecmwf.int/rest/ecmwfjsd/1.0/exporthtml/page?pageId=7373225
2. https://apps.ecmwf.int/codes/grib/format/grib2/
3. https://www.wmo.int/pages/prog/www/WMOCodes.html

However, much of the documentation seems to lead to documentation for ecCodes which replaced the GRIB-API in 2018. Since I am unable to access the original documentation, I am not sure which of the available documents is suitable to use.

**Comment by jswhit** [comment]
a pull request to update the links in the documentation would be welcome - I haven't had time to look into this yet.  It's fine to link to the eccodes docs, which replaced grib_api.

**Comment by jswhit** [comment]
fixed the URL in the docs
