### ISSUE TITLE
Directly modifying the regional value of gribmessage failed

### ISSUE THREAD

**Issue by MeteoBoy4** [jswhit/pygrib#15]
Hi jswhit,

I would like to modify the regional 'value' of one gribmessage in a GRIB file while keeping other 'value' unchanged, but the method which works in normal numpy environment (s=gribmessage.value[lat1:lat2,lon1:lon2] s[:,:]=10.) seems does not work with gribmessage.value, only changing the whole field all at once will make the it happened

So is there a simpler way to directly change the regional gribmessage.value ?

**Comment by jswhit** [comment]
how about

    data = gribmessage.values
    data[lat1:lat2,lon1:lon2 = 10  
    gribmessage.values = data

See the example set_bitmap.py.

**Comment by MeteoBoy4** [comment]
Yeah, that works of course, which changes the whole field all at once

That's pretty neat already, thanks so much

**Comment by jswhit** [comment]
Don't know what you mean by 'changing the whole field at once'?  You're only changing a subset of the grid.  Any time you change a grib message, the entire grib message must be unpacked and then re-packed.

**Comment by MeteoBoy4** [comment]
>Any time you change a grib message, the entire grib message must be unpacked and then re-packed
That's the point, I initially want to directly change grib.message[lat1：lat2, lon1,lon2] without creating another temp array, it seems not to work.

Thanks for your time really !
