### ISSUE TITLE
pygrib 2.0.5 setup.py incompatible with Python 2

### ISSUE THREAD

**Issue by oceandatalab** [jswhit/pygrib#155]
Hi,

It seems the latest release (2.0.5) published yesterday on Pypi cannot be installed in Python 2 environments. Installing the previous version (2.0.4) works fine.

In 2.0.5 the `setup.py` file opens `README.md` using the `encoding` argument, which is only available in Python 3.

If Python 2 is not supported anymore (it has been deprecated for some time now), then the Python 2 classifiers should be removed from `setup.py` .

If it was not intended, the problem is here: https://github.com/jswhit/pygrib/blob/4c298667dcdb5faf3d16a26bf38ebe45b1e0f6d9/setup.py#L197

Tested on ArchLinux:
> Python 2.7.18
> pip 20.2.4

and CentOS 8:
> Python 2.7.17
> pip 20.2.4

The error message:

```
 pip install pygrib                                                                   ] 10:24
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintain
ed. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.py
pa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting pygrib
  Using cached pygrib-2.0.5.tar.gz (21.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /mnt/workspace/2020-11-25_pygrib_issue/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-in
stall-7XeO9f/pygrib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7XeO9f/pygrib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(
__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-ba
se /tmp/pip-pip-egg-info-vjaaLQ
         cwd: /tmp/pip-install-7XeO9f/pygrib/
    Complete output (5 lines):
    reading from setup.cfg...Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7XeO9f/pygrib/setup.py", line 197, in <module>
        with open(os.path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jswhit** [comment]
will push out a 2.0.6 release with this fixed (it was not intentional). PR #156 adds 2.7 to the travis CI tests.

**Comment by wumpus** [comment]
While you're in there the tarball 2.0.5 has a setup.cfg in it, which seems like an accident @jswhit

**Comment by jswhit** [comment]
PR #156 merged, 2.0.6 tarball uploaded.

**Comment by wumpus** [comment]
This new tarball also has a setup.cfg file. That's a bug.

**Comment by wumpus** [comment]
I see you fixed setup.cfg bug in a checkin on November 29, 2020, by completely changing how setup.cfg was used. Guess I can remove the workaround now!
