### ISSUE TITLE
switch to or add new CI

### ISSUE THREAD

**Issue by wumpus** [jswhit/pygrib#157]
With Travis basically eliminating their free CI service, you're going to want to switch to another free service.

I have been moving my repos to azure-pipelines.

[Here are instructions for setting up the service, after you've created an azure-pipelines.yml file in your repo](https://openastronomy-azure-pipelines.readthedocs.io/en/latest/setup.html)

And [here is an azure-pipelines.yml from one of my projects that builds pygrib along the way.](https://github.com/wumpus/eht-met-forecast/blob/master/azure-pipelines.yml) [but it does not run your tests or compute your code coverage.]

If you like I could do a PR with working tests and code coverage. Then you'll  just have to do the setup at Azure.

**Comment by jswhit** [comment]
I didn't know that, but you're right - a new CI will be needed.  A pull request would be welcome.

**Comment by akrherz** [comment]
> With Travis basically eliminating their free CI service

That's not exactly true, is it?  Travis put out an updated [blog post](https://blog.travis-ci.com/oss-announcement) that calmed my fears at least.

**Comment by wumpus** [comment]
How many free OSS credits did they give you? I'm not seeing anyone reporting success.

**Comment by akrherz** [comment]
> How many free OSS credits did they give you? I'm not seeing anyone reporting success.

My understanding is that everyone gets 10,000 per month for building any public repos.  I have not tried to request more than that for OSS work. The issue that I am having is that it is not enough and the first paid tier level would not be sufficient either, so I have been working on Github Actions going to offload some of my Travis-CI work.

**Comment by akrherz** [comment]
> How many free OSS credits did they give you? I'm not seeing anyone reporting success.

I am sorry @wumpus , I was incorrect.  Yeah, those 10k credits are a one shot deal and getting OSS credits hasn't happened yet.  Yikes.
