### ISSUE TITLE
what happend with this, hlep~~

### ISSUE THREAD

**Issue by lovechang1986** [jswhit/pygrib#17]
:~/python/pygrib-master# python setup.py build
ok
ok
running build
running build_py
creating build/lib.linux-x86_64-2.7
copying ncepgrib2.py -> build/lib.linux-x86_64-2.7
running build_ext
building 'pygrib' extension
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aichang/anaconda/lib/python2.7/site-packages/numpy/core/include -Ig2clib_src -I/home/aichang/anaconda/include/python2.7 -c pygrib.c -o build/temp.linux-x86_64-2.7/pygrib.o
In file included from /home/aichang/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /home/aichang/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/aichang/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pygrib.c:313:
/home/aichang/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
pygrib.c:314:22: fatal error: grib_api.h: 没有那个文件或目录
 #include "grib_api.h"
                      ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by jswhit** [comment]
need to specify GRIBAPI_DIR so grib_api.h can be found

**Comment by lovechang1986** [comment]
thank you for reply.

           #grib_api_dir = /usr/local/gribapi
change setup.cfg file like this or the setup.cfg.template?

**Comment by jswhit** [comment]
See the *Install* section at

http://jswhit.github.io/pygrib/docs/index.html
