### ISSUE TITLE
NameError: name '__file__' is not defined

### ISSUE THREAD

**Issue by AgilentGCMS** [jswhit/pygrib#177]
I installed pygrib for python 2.7.17 from source, by setting ECCODES_DIR properly. The installation seemed to work. However, when I tried importing the pygrib module,
```python
In [1]: import pygrib
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-a1d2f888a334> in <module>()
----> 1 import pygrib

/discover/nobackup/projects/tm5var4d/packages/python/2.7.17/lib/python2.7/site-packages/pygrib-2.1.4-py2.7-linux-x86_64.egg/pygrib/__init__.py in <module>()
      1 # init for pygrib package
----> 2 from ._pygrib import *
      3 # Need explicit imports for names beginning with underscores
      4 from ._pygrib import __doc__, __version__

src/pygrib/_pygrib.pyx in init pygrib._pygrib()

NameError: name '__file__' is not defined
```
Help?

My eccodes is installed in a custom location, which is why I did not do `pip install pygrib`.

**Comment by AgilentGCMS** [comment]
I built pygrib for python 3.8.2 following the same procedure and imported pygrib, and that did not throw an error. So maybe this error is specific to python 2.7.x?

**Comment by AgilentGCMS** [comment]
Although, on python 3.8.2, I can't actually read an ECMWF grib file:
```python
In [2]: grbs = pygrib.open('ea-fc-20200901-1800-ml137-155-T255.gb')

In [3]: grbs
Out[3]: <pygrib._pygrib.open at 0x2aaad032ce20>

In [4]: for grb in grbs:
   ...:     grb
   ...:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-3c97bb731ad2> in <module>
----> 1 for grb in grbs:
      2     grb
      3

src/pygrib/_pygrib.pyx in pygrib._pygrib.open.__next__()

src/pygrib/_pygrib.pyx in pygrib._pygrib._create_gribmessage()

src/pygrib/_pygrib.pyx in pygrib._pygrib.gribmessage._set_projparams()

src/pygrib/_pygrib.pyx in pygrib._pygrib.gribmessage.__getitem__()

RuntimeError: b'Key/value not found'
```

**Comment by jswhit** [comment]
python 2.7 is no longer supported (it's not supported in the latest versions of  numpy either).

Can you zip that grib file and attach it to the issue? (or if it's too big put it on an ftp site somewhere)?

**Comment by AgilentGCMS** [comment]
Re: python 2.7, I was afraid of that.

You can download the grib file from [here](https://drive.google.com/file/d/1CZRC47BCHIvfOJhrySkqWcIE3BDiA8p_/view?usp=sharing). Note that this file (and others like this) are read by a transport model coded in Fortran, so I think the file itself is OK.

**Comment by jswhit** [comment]
OK, there are some keys that can't be read in that grib message that cause print(grb) to fail.  You can tell pygrib to ignore those keys by calling pygrib.tolerate_badgrib_on().  Or, just don't trigger the __repr__ method by printing the grb instance.
