### ISSUE TITLE
Is there any possibility that pygrib can be used on windows system without relying on cygwin environment?

### ISSUE THREAD

**Issue by bidhya** [jswhit/pygrib#19]

**Comment by jswhit** [comment]
would you be willing to test pull request #18?

**Comment by basaks** [comment]
Not working with anaconda + windows....anyone had any luck? Would be nice if I can support my software on windows.

```
[pyrate] C:\Users\sudipta>pip install git+https://github.com/jswhit/pygrib
Collecting git+https://github.com/jswhit/pygrib
  Cloning https://github.com/jswhit/pygrib to c:\users\sudipta\appdata\local\tem
p\pip-yia0qd-build
Installing collected packages: pygrib
  Running setup.py install for pygrib ... error
    Complete output from command C:\Users\sudipta\Anaconda2\envs\pyrate\python.e
xe -u -c "import setuptools, tokenize;__file__='c:\\users\\sudipta\\appdata\\loc
al\\temp\\pip-yia0qd-build\\setup.py';exec(compile(getattr(tokenize, 'open', ope
n)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record
c:\users\sudipta\appdata\local\temp\pip-1xrx7x-record\install-record.txt --singl
e-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    copying ncepgrib2.py -> build\lib.win-amd64-2.7
    running build_ext
    building 'pygrib' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\amd64\cl.exe /c /n
ologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\sudipta\Anaconda2\envs\pyrate\lib\sit
e-packages\numpy\core\include -Ig2clib_src -IC:\Users\sudipta\Anaconda2\envs\pyr
ate\include -IC:\Users\sudipta\Anaconda2\envs\pyrate\PC /Tcpygrib.c /Fobuild\tem
p.win-amd64-2.7\Release\pygrib.obj
    pygrib.c
    c:\users\sudipta\anaconda2\envs\pyrate\lib\site-packages\numpy\core\include\
numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, di
sable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    pygrib.c(242) : fatal error C1083: Cannot open include file: 'grib_api.h': N
o such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BI
N\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\sudipta\Anaconda2\envs\pyrate\python.exe -u -c "import setupto
ols, tokenize;__file__='c:\\users\\sudipta\\appdata\\local\\temp\\pip-yia0qd-bui
ld\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().repl
ace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\sudipta\appdata
\local\temp\pip-1xrx7x-record\install-record.txt --single-version-externally-man
aged --compile" failed with error code 1 in c:\users\sudipta\appdata\local\temp\
pip-yia0qd-build\
```

**Comment by jswhit** [comment]
you've got to build the grib_api c lib (and it's dependencies) first....

**Comment by basaks** [comment]
Thanks. Where can I get help on how to do that?

**Comment by jswhit** [comment]
the grib_api website? not sure, never tried building on windows

**Comment by jswhit** [comment]
see the link in pull request #18

**Comment by Marston** [comment]
Is there a way to install pygrib and pygrib2 together with Python3.6?
Attempts to install conda install -c conda-forge pygrib=2.0.1 results in:
UnsatisfiableError: The following specifications were found to be in conflict:
  - pygrib 2.0.1*
  - python 3.6*

**Comment by cqcn1991** [comment]
Is it possible to use in windows now?

**Comment by bidhya** [comment]
@cqcn1991 So far I have not been able with pygrib in windows. Workaround so far has been to use GDAL to work with grib files.

**Comment by blaylockbk** [comment]
Still having no luck installing pygrib on Windows.

**Comment by blaylockbk** [comment]
only slightly related, but could a workaround pygrib be to convert GRIB2 to HDF. Not sure how even do that on Windows.

**Comment by jdkloe** [comment]
another option here would be to use eccodes which is the successor of grib_api.
The build system for the eccodes library uses cmake which should make building on windows easier (although I never tried since I am not on that os).
See also: https://confluence.ecmwf.int/pages/viewpage.action?pageId=70949236

**Comment by vciulei** [comment]
@jdkloe  Currently tried to do it but got this error message. Anyone knows how to fix it ?

`CMake Warning at cmake/ecbuild_log.cmake:153 (message):
  WARN - ENABLE_LARGE_FILE_SUPPORT active, sizeof off_t is 4 < 8 but ecbuild
  does not know how to enable large files in this operating system
Call Stack (most recent call first):
  cmake/ecbuild_add_large_file_support.cmake:25 (ecbuild_warn)
  cmake/ecbuild_check_os.cmake:55 (ecbuild_add_large_file_support)
  cmake/ecbuild_system.cmake:236 (include)
  CMakeLists.txt:25 (include)


CMake Error at cmake/ecbuild_log.cmake:191 (message):
  CRITICAL - ecBuild is untested for this operating system: [Windows] --
  refusing to continue.  Disable this check with -DDISABLE_OS_CHECK=ON
Call Stack (most recent call first):
  cmake/ecbuild_check_os.cmake:383 (ecbuild_critical)
  cmake/ecbuild_system.cmake:236 (include)
  CMakeLists.txt:25 (include)`

Adding a boolean variable in my Cache did not work. [noob] in case you didn't figure it out so far. Any help is appreciated.

**Comment by jdkloe** [comment]
If you have issues with building eccodes you should report them here:
https://confluence.ecmwf.int/display/ECC/Reporting+a+bug+or+issue+in+ecCodes
Of course you could leave a link to the issue here as well for those interested to follow what happens at ECMWF.

**Comment by dopplershift** [comment]
eccodes is now buildable on windows. So in theory, it should be possible now to build pygrib on windows.

**Comment by dopplershift** [comment]
Indeed it is possible, just a small tweak (#122) needed.

**Comment by fernandoguzman2912** [comment]
The best solution that i found was install subsystem ubuntu in windows, because i can't install pygrib in anaconda promp.. 
You have go to microsoft store windows and install this ubuntu  y if you want to work in other partition disk, should mount the workspace with ' /mnt/d' "d" is other partition on the disk o another partition as example "e".

**Comment by fernandoguzman2912** [comment]
The best solution that i found was install subsystem ubuntu in windows, because i can't install pygrib in anaconda promp..
You have go to microsoft store windows and install this ubuntu y if you want to work in other partition disk, should mount the workspace with ' cd /mnt/d' "d" is other partition on the disk o another partition as example "e". Install pygrib in linux is easier than windows.

**Comment by dopplershift** [comment]
If `conda install -c conda-forge pygrib` is failing on Windows, I'd recommend opening an issue on the [conda-forge pygrib feedstock](https://github.com/conda-forge/pygrib-feedstock/issues/new/choose).

**Comment by zaheerkzz** [comment]
its end of 2022 and still pygrib not running on windows. is there a way i can make an executable using mac or linux for windows

**Comment by zaheerkzz** [comment]
there are other library options on windows. cfgrib, pupygrib, eccodes

**Comment by dopplershift** [comment]
@zaheerkzz You can get pygrib on Windows using conda and conda-forge: `conda install -c conda-forge pygrib`.

**Comment by zaheerkzz** [comment]
@dopplershift thank you.  i installed using conda and it worked on jupyter, but i want to make a windows executable for kivy, and it did't work there. all my other packages installed with pip.
