### ISSUE TITLE
pygrib can't open a file as a pathlib.Path object

### ISSUE THREAD

**Issue by blaylockbk** [jswhit/pygrib#193]
I get a TypeError when I try to open a grib file with a `pathlib.Path`. The work around is to convert the `pathlib.Path` to a string, but it would be convenient if pygrib could handle opening files with a `pathlib.Path`.

```python
import pygrib
from pathlib import Path

my_file = Path('./path/to/file.grib2')
grib = pygrib.open(my_file)
```
![image](https://user-images.githubusercontent.com/6249613/135317641-e03ef42f-60ec-4c77-a321-689d639e9de3.png)

**Comment by jswhit** [comment]
a pull request to implement this would be welcomed.
