### ISSUE TITLE
Import error:AttributeError: WKT2_2019

### ISSUE THREAD

**Issue by iamzdy** [jswhit/pygrib#195]
Windows10 python3.7
idle pycharm

**Comment by jswhit** [comment]
is that coming from the pyproj import?

**Comment by iamzdy** [comment]
> is that coming from the pyproj import?

Thanks for your replying. I am sorry that I did not give enough information. I did not find any solutions on Internet so I turned to you finally.
Yes, it comes from the pyproj import. 
File "D:\app\Anaconda3\lib\site-packages\pyproj\crs\crs.py", line 556, in CRS
    wkt_version: Union[WktVersion, str] = WktVersion.WKT2_2019
I am not familiar with python. I tried to re-install pyproj to a lower version and it works surprisingly.Thanks again!:)
