### ISSUE TITLE
Segmentation Fault with Operational HRRR files

### ISSUE THREAD

**Issue by rmeckman** [jswhit/pygrib#21]
Hello,

I have recently discovered that pygrib 1.9.8 is unable to read GRIB2 files that the National Centers for Environmental Prediction (NCEP) provides for the operational HRRR model. These files are available at  http://www.ftp.ncep.noaa.gov/data/nccf/nonoperational/com/hrrr/prod/. Here is some example code:

    >>> import pygrib
    >>> igrb = pygrib.open('hrrr.t00z.wrfsfcf05.grib2')
    >>> rr = igrb.message(1)
    >>> rr
    1:Maximum/Composite radar reflectivity:dB (instant):lambert:unknown:level 0 10:fcst time 5 hrs:from
    201511050000
    >>> rr_array = rr.values
    Segmentation fault (core dumped)

The file can be opened and a message read in, but any attempt to read the message data array using `.values` or `.data` results in a segmentation fault.

Further investigation suggests that the problem may be with the packing scheme used in these files. They use complex packing and spatial differencing (scheme 3 in grib_repack). If I use the wgrib2 utility to repack a file with another scheme (e.g., simple packing),  pygrib can read the file with no errors. Additionally, if I attempt to repackage a message using code similar to what is in grib_repack, I get the following errors:

    >>> rr['editionNumber']
    2
    >>> rr['dataRepresentationTemplateNumber']
    3
    >>> rr['dataRepresentationTemplateNumber'] = 0
    GRIB_API ERROR   :  unable to get groupSplittingMethodUsed as long (Key/value not found)
    GRIB_API ERROR   :  unable to get codedValues as double array (Key/value not found)
    GRIB_API ERROR   :  unable to get values as double array (Key/value not found) Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "pygrib.pyx", line 1141, in pygrib.gribmessage.__setitem__ (pygrib.c:12685)
    RuntimeError: b'Key/value not found'

This looks to me like pygrib is looking for some packing parameters that do not exist in the message.

This problem is occurring on a 64-bit Ubuntu linux machine. Has anyone else encountered this problem or have an explanation of what is different about these files?

Regards,
    Rick

**Comment by jswhit** [comment]
The problem has been fixed in later versions of pygrib by using the NCEP g2clib for unpacking grib messages that use 'complex packing with spatial differencing'.  The grib_api does not handle this type of packing.  I've confirmed that the github master can read and unpack the grib messages in the HRRR grib file.
