### ISSUE TITLE
`latlons` errors with 'float' object is not subscriptable

### ISSUE THREAD

**Issue by Ge0rges** [jswhit/pygrib#235]
Hello,

I'm using `pygrib` to read data downloaded from `cdsapi` which provides a GRIB file. Here's how:

```
grbs = pygrib.open(grib_file_path)
    grb = grbs[1]
    data = grb.values

    # Get the latitudes and longitudes from the GRIB file
    lats, lons = grb.latlons()
```

In some cases the last line gives me the following error:
```
  File "/Users/GeorgesKanaan/micromamba/envs/jupyter/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-0dac3669accf>", line 1, in <module>
    grb.latlons()
  File "src/pygrib/_pygrib.pyx", line 1540, in pygrib._pygrib.gribmessage.latlons
TypeError: 'float' object is not subscriptable
```

Attached is the pygrib file causing this issue (renamed to `.txt` for GitHub originally `.grib`)
[download_10.42047127134399_81.01965522454935_2023-05-19.txt](https://github.com/jswhit/pygrib/files/14198292/download_10.42047127134399_81.01965522454935_2023-05-19.txt)

**Comment by jswhit** [comment]
there is only 1 latitude in that file (so the data is 1d instead of 2d).  latlons only works with 2d grids.

```
Ni = 1440
Nj = 1
latitudeOfFirstGridPoint = 81010
latitudeOfFirstGridPointInDegrees = 81.01
longitudeOfFirstGridPoint = 10420
longitudeOfFirstGridPointInDegrees = 10.42
```

**Comment by jswhit** [comment]
you can use 'latitudes' and 'longitudes' keys - they do work in this case

**Comment by jswhit** [comment]
I've created a [PR](https://github.com/jswhit/pygrib/pull/236) with a very simple fix for this (so latlons will work when only 1 latitude is present in grid).
