### ISSUE TITLE
pygrib and Python 3.5

### ISSUE THREAD

**Issue by pmarshwx** [jswhit/pygrib#24]
I'm unable to run a successful test suite using Python 3.5. Has anyone else had better luck/success? 

I'm attaching both my (test) conda environment and the output from running the test suite.  I'm using grib-api build/installed via homebrew.

[env.yaml.txt](https://github.com/jswhit/pygrib/files/93789/env.yaml.txt)
[test.log.txt](https://github.com/jswhit/pygrib/files/93790/test.log.txt)

I have added a .txt extension to allow for uploading in Github.

**Comment by jswhit** [comment]
fix is in pull request #25

**Comment by pmarshwx** [comment]
I'll go test it.

**Comment by pmarshwx** [comment]
As I commented in the pull request, the pull request fixes my (known) issues with Python 3.5.

**Comment by jswhit** [comment]
pull request #25 merged, closing now
