### ISSUE TITLE
Performance issue with area extraction

### ISSUE THREAD

**Issue by stephane-21** [jswhit/pygrib#244]
Hello,

I have written this script which shows that pygrib is really slow when cropping data from a big grib2 file.
The template file I am using is a 638 MiB from a DWD German model.

With pygrib it takes **46.5 sec** to read and crop weather maps.
In comparison, if i use "cdo+pygrib" (https://code.mpimet.mpg.de/projects/cdo/wiki/Tutorial) it takes only **1.9 sec**.

I think there is a performance issue with this "pygrib.message.data()" command. In fact, it takes as long as if I was uncompressing first the full grib2 messages (full earth), and only then cropping the data.

**Read and crop with pygrib**
```
import os
import time
import pygrib

input_file = "dataset/P_3d_T_001_202404290000.grb2"
output_file = "output/P_3d_T_001_202404290000.grb2"
north = 50
south = 40
west = 20
east = 30

t0 = time.time()
grib_data = []
grib_file = pygrib.open(input_file)
for grib_message in grib_file:
    data, _, _ = grib_message.data(lat1=south, lat2=north, lon1=west%360, lon2=east%360)
    grib_data.append(data)
print(round(time.time() - t0, 2))  # 46.46 s
```

**Crop with CDO +  read with pygrib**
```
import os
import time
import pygrib

input_file = "dataset/P_3d_T_001_202404290000.grb2"
output_file = "output/P_3d_T_001_202404290000.grb2"
north = 50
south = 40
west = 20
east = 30

t0 = time.time()
os.system(f"cdo -f grb2 sellonlatbox,{west},{east},{south},{north} {input_file} {output_file}")

grib_data_2 = []
grib_file = pygrib.open(output_file)
for grib_message in grib_file:
    data = grib_message.values
    grib_data_2.append(data)
print(round(time.time() - t0, 2))  # 1.91 s
```

**Comment by jswhit** [comment]
In fact, pygrib is reading the whole grib message and then cropping the data.  I don't think it's possible to uncompress just a part of a grid message.  I presume the reason cdo is faster is that it is doing the cropping by looping with C code (pygrib is using numpy indexing with boolean masks).

**Comment by stephane-21** [comment]
I also always thought that the grib2 format of 1 message is like a "solid archive".

I did some additional tests with CDO, extracting a 0.1deg x 0.1deg area (single points) takes the same duration as extracting a 10deg x 10deg area (1.91 sec).
And extracting a 40deg x40deg area takes 2.09 sec (only 10% more).
So, you are right, it looks like that in all cases CDO is scanning the full earth maps in 2 sec, which I was not expecting to be so quick.
