### ISSUE TITLE
How to check the ECCODES C library version used when installed with pip?

### ISSUE THREAD

**Issue by LuchiLucs** [jswhit/pygrib#247]
As stated in the title, how to check the version of the C library used when installing with pip? Is there a way to upgrade the C library? Can I benefit in doing so w.r.t to speed or consistency optimizations?

**Comment by jswhit** [comment]
```
>>> import pygrib
pygrib.grib_api_version
>>> pygrib.grib_api_version
'2.35.0'
>>>
```

You can build from source against your own version of eccodes - but I doubt that will resuit in any significant change in performance.
