### ISSUE TITLE
How to select messages based on a boolean callable

### ISSUE THREAD

**Issue by LuchiLucs** [jswhit/pygrib#249]
I wish to select grib messages based on a boolean expression which can be call on the iterable grib so that to implement custom filtering logic. In my case I wish to filter based on the fact that either name or parameterName is valid and their content is contained in a container. For instance something like this:

```
def grib_select_callable(grb: pygrib.gribmessage, variables: list[str]) -> bool:
    return (grb.valid_key('name') and grb.name in variables) or (grb.valid_key('parameterName') and grb.parameterName in variables)
```

Is it possible to implement this logic efficiently? I did not find any way to filter based on multiple expression with the OR logic (select seems based on the AND logic of its kwargs)

**Comment by jswhit** [comment]
You can use a callable in [pygrib.open.select](https://jswhit.github.io/pygrib/api.html#pygrib.open.select).
