### ISSUE TITLE
Extracting data at paticular level

### ISSUE THREAD

**Issue by wxguy** [jswhit/pygrib#26]
Is there any documentation regarding the subject matter? I am trying to plot upper wind from GFS data. I have not found any documentation for this.

**Comment by jswhit** [comment]
use the select method of the grib message instance, and pass it a level keyword.

**Comment by wxguy** [comment]
A simple example code would be of great help.

**Comment by jswhit** [comment]
Here's some code from test.py:

   
    >>> grbs = pygrib.open('sampledata/gfs.grb')
    >>> sel_grbs = grbs.select(shortName='t',level=500)
    >>> for grb in sel_grbs: grb
    101:Temperature:K (instant):regular_ll:isobaricInhPa:level 50000 Pa:fcst time 72 hrs:from 201110080000
    >>> sel_grbs = grbs.select(shortName='t',level=(850,700,500))
    >>> for grb in sel_grbs: grb
    101:Temperature:K (instant):regular_ll:isobaricInhPa:level 50000 Pa:fcst time 72 hrs:from 201110080000
    133:Temperature:K (instant):regular_ll:isobaricInhPa:level 70000 Pa:fcst time 72 hrs:from 201110080000
    157:Temperature:K (instant):regular_ll:isobaricInhPa:level 85000 Pa:fcst time 72 hrs:from 201110080000

**Comment by wxguy** [comment]
Thanks for the answer. It would be really helpful for a newbie if he find the same code on the documentation page.

Yo may close the issue.
