### ISSUE TITLE
libgrib_api.so cannot be found

### ISSUE THREAD

**Issue by tomaso909** [jswhit/pygrib#39]
I just installed pygrib. I get this error when importing it:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libgrib_api.so: cannot open shared object file: No such file or directory
```

I have libgrib_api.so located in /usr/local/lib.
grib_api is located in /usr/local/share. This is my setup.cfg file:

```
[directories]
grib_api_dir = /usr/local/share
# install man pages for command line utilities here
man_dir = /usr/local/man
[files]
# uncomment and set to grib_api library name.
# If you are using GRIB-API with MSVS, library name might be 'grib_api_lib'.
grib_api_libname = grib_api_lib
```
I am not sure about the value I should be setting grib_api_libname to. Perhaps that's the issue.

**Comment by jswhit** [comment]
I think you can just set

grib_api_dir=/usr/local
