### ISSUE TITLE
NWS NDFD Valid Times

### ISSUE THREAD

**Issue by Pkamis** [jswhit/pygrib#40]
I've noticed the National Weather Service NDFD grib files have a tag "stepRange" which seems to be causing the pygrib created variable "validDate" to be set incorrectly to the end of the "stepRange".  

While not a huge issue,  it did cause some confusion on the intended valid times of the messages.  I'm not sure if this is a bug in pygrib, or maybe NWS is encoding their messages/files in some awkward way. It does look like the section of code that creates "validDate" assumes stepRange always indicates the proper validTime, which perhaps is not be a safe assumption?

**Comment by jswhit** [comment]
The code uses stepRange to define the forecast time.  The validDate is set using the end of the stepRange.  So, for example, if stepRange='12-24' and analDate=2016010100, the validDate will be set to 2016010200.  This works for every NDFD file I've tried.  Can be more specific about the problem you're seeing?  Perhaps post a sample file?

**Comment by Pkamis** [comment]
An example would be the attached file for a PoP12 forecast.  The first message has a "forecastTime" of 12 (in hours) and taken with the "analDate" of 2016-07-02T00:00:00Z should give a valid time of 2016-07-02T12:00:00Z.  However if you use the interpreted var "validTime" from pygrib, because of it's use of "stepRange" of 12-24, it gives 2016-07-03T00:00:00Z.

I've confirmed with the NWS that the first valid time is the correct one, and am awaiting confirmation of their use of "stepRange" in this case.  

[ndfd_2016070200_conus_PoP12.grb2.zip](https://github.com/jswhit/pygrib/files/418418/ndfd_2016070200_conus_PoP12.grb2.zip)

**Comment by jswhit** [comment]
There are also  'validtyDate' and 'validityTime' keys that grib_api sets to 20160702 and 1200.  I recall the reason I ended up using stepRange to define validDate was because the forecastTime key is not always set.  Perhaps I should use forecastTime if available, then fall back on stepRange.

**Comment by Pkamis** [comment]
In this case, 'validityDate' + 'validityTime' were what we ended up using, and what was suggested by the NWS after contacting them.  I think you're proposed solution would work just fine, especially since the gribs you've tested that don't set 'forecastTime', would remain un-affected.

**Comment by jswhit** [comment]
OK, implemented in pull request #41
