### ISSUE TITLE
Trouble with converting GRIB2 to GRIB1 using the cnvgrib2to1 

### ISSUE THREAD

**Issue by exodetzu** [jswhit/pygrib#45]
I'm trying to convert GRIB2 to GRIB1 using the cnvgrib2to1 located at the utils folder. I'm getting the data file from this link: ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/hourly/prod/ but it seems that it is not successful. I would appreciate any help with this! 

![image](https://cloud.githubusercontent.com/assets/22829884/19375413/57660b98-9206-11e6-9b49-38dcc044662a.png)

**Comment by jswhit** [comment]
The grib_api library can only transfer a subset of GRIB2 variables into GRIB1. Unfortunately, there's nothing I can do about this.

**Comment by exodetzu** [comment]
Oh, I see. Thank you for your help @jswhit.
