### ISSUE TITLE
Cygwin installation instructions missing

### ISSUE THREAD

**Issue by snowman2** [jswhit/pygrib#49]
Page for Cygwin installation instructions is missing.

**Comment by lanceberc** [comment]
The link referenced in all of the pygrib docs [http://code.google.com/p/pygrib/wiki/CygwinWindowsInstall](http://code.google.com/p/pygrib/wiki/CygwinWindowsInstall)
redirects to https://github.com/jswhit/pygrib. Are there cygwin install instructions somewhere?

**Comment by snowman2** [comment]
Closing as WSL has removed the need for cygwin and wheels exist now.
