### ISSUE TITLE
GRIB sample data

### ISSUE THREAD

**Issue by hugovk** [jswhit/pygrib#54]
I'm a member of the open-source Pillow imaging library for Python.

https://github.com/python-pillow/Pillow

I'm trying to increase test coverage of the 20-year-old-plus code base by adding unit tests for more file formats.

Pillow has very limited GRIB support: only a stub that can recognise the format. Read and write would require an extra handler. Nevertheless, I'd like to test what is there.

Would it be possible to use and redistribute GRIB files from https://github.com/jswhit/pygrib/tree/master/sampledata/ in the Pillow codebase as part of the test suite?

Pillow uses an open source PIL Software License: https://github.com/python-pillow/Pillow/blob/master/LICENSE

Thank you!

**Comment by jswhit** [comment]
Sure, I see no problem using and redistributing those files.

**Comment by hugovk** [comment]
Thank you!
