### ISSUE TITLE
Future of this package in light of ecCodes?

### ISSUE THREAD

**Issue by cpaulik** [jswhit/pygrib#59]
Just wanted to ask what the future plans of this package are in light of the [ecCodes](https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home) development and the proposed [Python interface](https://software.ecmwf.int/wiki/display/ECC/High-level+Pythonic+Interface+in+ecCodes)?

**Comment by jswhit** [comment]
I'll support this module as long as people find it useful - but the ecCodes interface does seem to be the way of the future.

**Comment by cpaulik** [comment]
Thanks, good to hear. I was just doing some research to see if/when we should make the switch to eccodes in our packages.
