### ISSUE TITLE
Efficient download of messages from remote grib2 without inventory

### ISSUE THREAD

**Issue by acowlikeobject** [jswhit/pygrib#60]
Hi,

Is there a way to select byte ranges in a grib2 file on a remote server if there is no inventory file?  In other words, can an inventory of messages be built without downloading the entire grib2 file?

In theory, there must be a way to do one pass to read only message headers (and get the byte ranges), but not sure if pygrib provides a way to do that.

Thanks.

**Comment by jswhit** [comment]
There is some code in issue #42 that shows how parse a grib file (provided as a binary string) into a sequence of grib messages, including finding the offsets and lengths.  Don't think this allows you to generate an inventory without reading all the bytes though.

**Comment by acowlikeobject** [comment]
Seems promising. Is there a known number of bytes that form a header from which pygrib could tell me the level, endStep, etc. of that message?  (I'm not sure if a `pygrib.fromstring()` on just a header with no data would cause it to barf.)  I'm trying to avoid having to download the actual data for every message.

Big picture is that HAS files are giant tars.  Since the tars are uncompressed, we can efficiently build an inventory of its contents (what byte range each grib file is in within the tar) without downloading it (just skipping ahead to the tar headers).

If we could take it a step further and "read" the header bytes of each grib file and determine if we want it, then we wouldn't have to download 250GB of tars to use [5GB] of data.  We'd get reasonably close to random access.

**Comment by jswhit** [comment]
Don't know off the top of my head, would have to read the GRIB spec.

**Comment by acowlikeobject** [comment]
All right, I'll close this out for now.  I don't think I have time at the moment to dig deeper into the spec either.

**Comment by pfwnicks** [comment]
Is there any progress made on this?
