### ISSUE TITLE
future plans?

### ISSUE THREAD

**Issue by jdkloe** [jswhit/pygrib#61]
ECMWF has fully moved to the new ecCodes library now (which provides its own python interface), and will only provide limited support for GRIB_API, e.g. tables and urgent bug fixes, but this will end in the autumn of 2018. 
What will happen with pygrib after that? Will it be discontinued? Or will you provide a wrapper to the new ecCodes library?

**Comment by jswhit** [comment]
Don't know - haven't had time to look at the ecCodes python interface to see if it makes pygrib redundant.  Have you used it?

**Comment by jdkloe** [comment]
I did some simple tests a few releases ago, which where not very encouraging, so I decided to try again with the latest version (release v2.3.0). Main outcome:
- it is possible to open a grib file and iterate over its grib messages
- it is possible to request key values or inspect available keys
However:
- it is not possible to easily get lat-lon  information in an array, I only found a way to get the values for a given point at a time. Ofcourse you could construct this yourself for a regular grid, but for more complicated grids this is not obvious
- it is not possible to get values for keys that contain an array of values (like pl or distinctLatitudes). So it is not possible at all to get lat-lon values for reduced Gaussian grids through the python interface.
I did not study the fortran or c interfaces, so maybe there is a workaround through that route, or maybe I did not look hard enough

I get the feeling that this python interfaces in eccodes is still not very mature, so at this point in time it surely is no replacement for pygrib. Maybe a future release will be.

**Comment by jdkloe** [comment]
In addition, ecCodes currently does not support python3, which also is a major issue. 
For later reference, here is the code I used to test:
`
#!/usr/bin/env python
# python3 is not yet supported ...

# see for more examples:
# https://software.ecmwf.int/wiki/display/ECC/GRIB+examples

import os, sys

eccodes_path = os.path.join('/usr/people/kloedej/temp_ectrans/bufr_stuff',
                            'eccodes_sources/eccodes-2.3.0-install',
                            'lib64/python2.7/site-packages')
sys.path.insert(0, eccodes_path)
import eccodes

fn = 'gribfile_20140531.u10s.grib'
keys = ['Ni', 'Nx', 
        'Nj', 'Ny',
        'pl', # does not work ...
        'latitudeOfFirstGridPointInDegrees',
        'longitudeOfFirstGridPointInDegrees',
        'latitudeOfLastGridPointInDegrees',
        'longitudeOfLastGridPointInDegrees',
        'latitudes', # does not work ...
        'distinctLatitudes'] # does not work ...

f = open(fn)
while True:
    gid = eccodes.codes_grib_new_from_file(f)
    if gid is None:
        break
    for key in keys:
        try:
            print '  %s: %s' % (key, eccodes.codes_get(gid, key))
        except eccodes.CodesInternalError as err:
            print 'Error with key="%s" : %s' % (key, err.msg)

    iterid = eccodes.codes_keys_iterator_new(gid, 'ls')
    while eccodes.codes_keys_iterator_next(iterid):
            keyname = eccodes.codes_keys_iterator_get_name(iterid)
            keyval = eccodes.codes_get_string(iterid, keyname)
            print "%s = %s" % (keyname, keyval)
 
    values = eccodes.codes_get_values(gid)
    print 'type(values) = ', type(values)
    print 'values.shape = ', values.shape
    print 'values = ', values

    # note: the only method that gives lat,lon values seems to
    # be eccodes.grib_iterator_next, but this does only provide lat, lon for
    # a single point, not an array ....

    # this works:
    v = eccodes.codes_get_array(gid, "values")
    print('v=', v)

    # but this does not work
    #lat = eccodes.codes_get_array(gid, "latitude")
    #lon = eccodes.codes_get_array(gid, "longitude")

    print 'There are %d values, average is %f, min is %f, max is %f' % (
            eccodes.codes_get_size(gid, 'values'),
            eccodes.codes_get(gid, 'average'),
            eccodes.codes_get(gid, 'min'),
            eccodes.codes_get(gid, 'max')
        )
 
    eccodes.codes_release(gid)
    # read just one grib msg for this example
    break

f.close()
`
And here the output I get:
`
>./eccodes_python_test.py 
  Ni: 2147483647
  Nx: 2147483647
  Nj: 256
  Ny: 256
ECCODES ERROR   :   wrong size (1) for pl it contains 256 values 
Error with key="pl" : Passed array is too small
  latitudeOfFirstGridPointInDegrees: 89.462
  longitudeOfFirstGridPointInDegrees: 0.0
  latitudeOfLastGridPointInDegrees: -89.462
  longitudeOfLastGridPointInDegrees: 359.296
Error with key="latitudes" : Passed array is too small
Error with key="distinctLatitudes" : Passed array is too small
edition = 1
centre = ecmf
typeOfLevel = surface
level = 0
dataDate = 20140530
stepRange = 12
dataType = fc
shortName = u10n
packingType = grid_simple
gridType = reduced_gg
type(values) =  <type 'numpy.ndarray'>
values.shape =  (88838,)
values =  [-2.68859863 -3.38586426 -4.0177002  ..., -5.44543457 -4.82141113
 -3.74328613]
('v=', array([-2.68859863, -3.38586426, -4.0177002 , ..., -5.44543457,
       -4.82141113, -3.74328613]))
There are 88838 values, average is -0.597574, min is -31.595825, max is 24.356323
>
`

**Comment by jswhit** [comment]
OK, thanks for that.  According to the web page, ecCodes is backwards compatible with grib_api, so pygrib should build against it with just minor mods to setup.py.  I'll see if I can create a pull request for this in the next week or so.

**Comment by jdkloe** [comment]
A small addition: after discussing the issue with an expert at ECMWF it seems I overlooked some functionality. Getting an array of values from a key is possible afteral. You could use some code like this:
```
keysize = eccodes.codes_get_size(gid, key)
if keysize == 1:
    # this gives you an int or a float or a string
    scalar_value = eccodes.codes_get(gid, key)
else:
    # this gives you a numpy.ndarray
    array_of_values = eccodes.codes_get_array(gid, key)
```
or simply use:
```
scalar_or_array = eccodes.codes_get_array(gid, key)
```
which always gives you a numpy.ndarray of 1 or more elements (except maybe for string values, but I did not test that)

**Comment by jdkloe** [comment]
ECMWF also informed me that they are working on support for python3, but they could not give a date yet.

**Comment by jdkloe** [comment]
@jswhit 
Did you already have an opportunity to look into the eccodes interfacing?

**Comment by jswhit** [comment]
eccodes works now, just use setup.cfg and change library name from grib_api to eccodes (last line in setup.cfg.template)

**Comment by jdkloe** [comment]
thanks.

**Comment by jdkloe** [comment]
just tested this and I can confirm that pygrib builds and runs fine with eccodes on Fedora 28, both with python2 and python3.
