### ISSUE TITLE
iScansNegatively, jScansPositively

### ISSUE THREAD

**Issue by kzarns** [jswhit/pygrib#7]
I have a use case which relies on interpretation of those two values as seen in versions prior to version 1.9.8.  Would it be possible to make this behavior configurable within pygrib so that the library could be directed to follow grib_api standard or follow the interpretation of those values?  I don't know if this would take the form of an argument to open, an alternative open function, a internal pygrib variable or what would make the most sense.  I do not think there is a similar precedent to follow for pygrib.

**Comment by jswhit** [comment]
the value of those two parameters is not set by pygrib, it is the value encoded in the grib file and returned by grib_api
