### ISSUE TITLE
Pylint give errors

### ISSUE THREAD

**Issue by fox91** [jswhit/pygrib#70]
I don't know if there is an issue in Pylint or in your code, but using Pylint when I use pygrib give me errors like these:
```
$ pylint my_source.py
No config file found, using default configuration
************* Module my_source
...
E: 24,15: Module 'pygrib' has no 'open' member (no-member)
E: 26,16: Module 'pygrib' has no 'index' member (no-member)
...
```

**Comment by exhuma** [comment]
Without having your code (especially the import lines & lines which pylint complains about) it is almost impossible to tell. But this rather looks like an error in your own code, or pylint is unable to determine the members of pygrib.

But in any case it's likely that this is unrelated to pygrib.

**Comment by fox91** [comment]
Running `pylint` with `extension-pkg-whitelist` option doesn't give me anymore that error.
```bash
pylint -f colorized --extension-pkg-whitelist=pygrib my_source.py
```
