### ISSUE TITLE
having problem with grib.select

### ISSUE THREAD

**Issue by frozt** [jswhit/pygrib#8]
Hi,
On my local I have pygrib 1.9.8 is installed and I have the script to process grib2 file format. It works perfectly on my local but when I try to run it on another machine with pygrib 2.0.0 installed, I am getting "grib_accessor_class_codetable.c at line 316: assertion failure Assert(isdigit(*p))" message and script doesn't proceed or exit. I get the message when I call 
grib2.select(name='U component of wind')
What may cause this message?

**Comment by jswhit** [comment]
I have no idea.

**Comment by frozt** [comment]
The problem was grib_api itself. For ubuntu 14.04, installing libgrib-api-dev works fine but with ubuntu 12.04 we were having this problem. Installing grib_api-1.10.4 manually on ubuntu 12.04 solved the problem.
