### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eengl** [jswhit/pygrib#80]
Hi Jeff,

Just wondering when can we expect a new release that allows the user to choose what to install (what I worked on a while back ad you accepted).

Thanks,
Eric

**Comment by opoplawski** [comment]
Would be good to have the eccodes support as well.

**Comment by floresfdev** [comment]
Hi @opoplawski, I was looking for that as well, and apparently ecCodes is currently being supported. Among other commits, I've found a merged PR with some minor but relevant changes to the documentation: https://github.com/jswhit/pygrib/commit/95ea3559907c79adefd01fcf30e1bf3c920a8a81

**Comment by jdkloe** [comment]
pygrib now builds and runs with eccodes as replacement for grib_api. See these related issues:
https://github.com/jswhit/pygrib/issues/59
https://github.com/jswhit/pygrib/issues/61
I think the addition of eccodes support is sufficient reason to do a new release. Linux packagers will need to upgrade when grib_api goes out of support at ECMWF end of this year, and a new release is the most clear way of providing this new feature.

**Comment by jswhit** [comment]
version 2.0.3 released - uses libeccodes by default
