### ISSUE TITLE
'step' key not working in selector

### ISSUE THREAD

**Issue by julienvienne** [jswhit/pygrib#9]
Hello Jeffrey,

This is not really an issue, but mostly an improvement request.
I would like to have the 'step' attribute (timestep of grib message) accessible by grib selector function.
Let me explain. Here is a piece of code to extract tmax field from GFS file (ftp://ftp.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.2015031600/gfs.t00z.pgrb2.0p25.f006). 

>>>import pygrib
>>>grib_file=pygrib.open('gfs.t00z.pgrb2.0p25.f006')
>>>tmax_msg = grib_file.select(level=2,shortName='tmax', 'typeOfLevel': 'heightAboveGround')[0]

Here I didn't use the 'step' attribute to get the message and the extract works fine. However, I'm not sure that the selection will return only one message due to missing timestep condition (I know this is a one timestep file, but I need my code to be more generic, and some ECMWF files contain multiple timesteps). So I would like to be more specific in my selection map. The step attribute seems to appear in message field :
>>>print(tmax_msg['step'])
6

But if I add this attribute to filter, I get a data not found exception:
>>>tmax_msg = grib_file.select(level=2,shortName='tmax', 'typeOfLevel': 'heightAboveGround', step=6)[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygrib.pyx", line 609, in pygrib.open.select (pygrib.c:5851)
ValueError: no matches found

Apparently, only the 'stepRange' attribute can be used to filter over timesteps, but it is quite annoying because this field depends on parameter :
tmax -> stepRange = '0-6'
2t -> stepRange = '6'

Do you think it could be possible to use the 'step' attribute as a common timestep filter for all parameter ?

Best regards

Julien

**Comment by jswhit** [comment]
Julien: If you create an issue on the gitub site, I promise to look into
this.

-Jeff

On Tue, Mar 17, 2015 at 11:48 AM, julienvienne <notifications@github.com>
wrote:

> Hello Jeffrey,
>
> This is not really an issue, but mostly an improvement request.
> I would like to have the 'step' attribute (timestep of grib message)
> accessible by grib selector function.
> Let me explain. Here is a piece of code to extract tmax field from GFS
> file (
> ftp://ftp.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.2015031600/gfs.t00z.pgrb2.0p25.f006).
>
>
>  import pygrib
> grib_file=pygrib.open('gfs.t00z.pgrb2.0p25.f006')
> tmax_msg = grib_file.select(level=2,shortName='tmax', 'typeOfLevel':
> 'heightAboveGround')[0]
>
>  Here I didn't use the 'step' attribute to get the message and the
> extract works fine. However, I'm not sure that the selection will return
> only one message due to missing timestep condition (I know this is a one
> timestep file, but I need my code to be more generic, and some ECMWF files
> contain multiple timesteps). So I would like to be more specific in my
> selection map. The step attribute seems to appear in message field :
>
>  print(tmax_msg['step'])
> 6
>
>  But if I add this attribute to filter, I get a data not found exception:
>
>  tmax_msg = grib_file.select(level=2,shortName='tmax', 'typeOfLevel':
> 'heightAboveGround', step=6)[0]
> Traceback (most recent call last):
> File "", line 1, in
> File "pygrib.pyx", line 609, in pygrib.open.select (pygrib.c:5851)
> ValueError: no matches found
>
>  Apparently, only the 'stepRange' attribute can be used to filter over
> timesteps, but it is quite annoying because this field depends on parameter
> :
> tmax -> stepRange = '0-6'
> 2t -> stepRange = '6'
>
> Do you think it could be possible to use the 'step' attribute as a common
> timestep filter for all parameter ?
>
> Best regards
>
> Julien
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jswhit/pygrib/issues/9>.
>



-- 
Jeffrey S. Whitaker
NOAA/OAR/PSD  R/PSD1
325 Broadway, Boulder, CO, 80305-3328
Phone: (303)497-6313
FAX: (303)497-6449

**Comment by jswhit** [comment]
Oops - I see it's already here!  I'm on it.

**Comment by jswhit** [comment]
fix in pull request #10 (branch issue9)

**Comment by julienvienne** [comment]
Hello,

Thank you for your reactivity.
I've updated pygrib.pyx source code with your modifications and rebuild the
package, but I still have the same problem.

In order to test, I have completed your test suite (see attachement file)
with one test that should work but fails on my side :

 86     same as previous test, adding 'step' condition
 87     >>> selected_grbs =
grbs.select(level=2,typeOfLevel='heightAboveGround*', step=120*) # get all
2-m level fields, *at timestep 120h*
 88     >>> for grb in selected_grbs: grb
 89     3:Maximum temperature:K
(instant):regular_gg:heightAboveGround:level 2 m:fcst time 108-120 hrs:from
200402291200
 90     4:Minimum temperature:K
(instant):regular_gg:heightAboveGround:level 2 m:fcst time 108-120 hrs:from
200402291200


Could you confirm that point on your side ?

Best regards,



2015-03-18 3:46 GMT+01:00 Jeff Whitaker <notifications@github.com>:

> fix in pull request #10 <https://github.com/jswhit/pygrib/pull/10>
> (branch issue9)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jswhit/pygrib/issues/9#issuecomment-82697778>.
>



-- 

Julien VIENNE
Responsable SI
Ingénieur Projets

*climpact**-**metnext*

79, rue du Faubourg Poissonnière, 75009 PARIS
Tel: +33(0)155 078 575
Mobile: +33(0)672 00 70 60
Website: www.climpact.com / www.metnext.com

**Comment by jswhit** [comment]
I added an extra test in test.py as you suggest, and it works for me.

the updated test.py has been committed to the issue9 branch.  

Are you sure you actually installed the issue9 branch, and not master?

**Comment by jswhit** [comment]
Julien: Is this issue resolved if you generate pygrib.c with cython?

**Comment by jswhit** [comment]
went ahead and merged pull request #10.  Closing this issue for now - if you still have a problem please reopen.
